"""AddPasswordHashAndEmailVerified

Revision ID: 07e68cdffe94
Revises: 8c2e36771705
Create Date: 2026-06-21 18:29:38.001134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07e68cdffe94'
down_revision: Union[str, None] = '8c2e36771705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citizens', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('citizens', sa.Column('is_email_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('citizens', 'is_email_verified')
    op.drop_column('citizens', 'password_hash')
    # ### end Alembic commands ###
