"""initial

Revision ID: 4f83b56ed279
Revises: None
Create Date: 2026-05-29 18:14:01.483338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f83b56ed279'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('citizens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('verification_status', sa.Enum('unverified', 'pending', 'verified', 'rejected', name='verification_status_enum'), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('home_district_id', sa.UUID(), nullable=True),
    sa.Column('living_in_district_id', sa.UUID(), nullable=True),
    sa.Column('account_status', sa.Enum('active', 'suspended', 'deleted', name='account_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['home_district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['living_in_district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('desired_outcome', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('roads', 'water', 'electricity', 'health', 'education', 'environment', 'publicSafety', 'governance', name='issue_category_enum'), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('district_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'underReview', 'published', 'active', 'resolved', 'archived', 'rejected', 'merged', name='issue_status_enum'), nullable=False),
    sa.Column('support_count', sa.Integer(), nullable=False),
    sa.Column('oppose_count', sa.Integer(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('merged_into_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['citizens.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['merged_into_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_issues_category', 'issues', ['category'], unique=False)
    op.create_index('ix_issues_created_at', 'issues', ['created_at'], unique=False)
    op.create_index('ix_issues_district_status', 'issues', ['district_id', 'status'], unique=False)
    op.create_index('ix_issues_search_vector', 'issues', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('moderation_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('moderator_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.Enum('issue', 'comment', 'evidence', name='mod_target_type_enum'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Enum('approve', 'reject', 'merge', 'clarify', 'hide', 'restore', name='mod_action_type_enum'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['moderator_id'], ['citizens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('citizen_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('issueApproved', 'issueRejected', 'clarificationRequested', 'participationReceived', 'appealUpdate', 'resolutionUpdate', name='notification_kind_enum'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verification_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('citizen_id', sa.UUID(), nullable=False),
    sa.Column('verification_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('pending', 'valid', 'invalid', 'expired', name='ver_record_status_enum'), nullable=False),
    sa.Column('uidai_ref', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appeals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('citizen_id', sa.UUID(), nullable=False),
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'reviewed', 'upheld', 'overturned', name='appeal_status_enum'), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['moderation_actions.id'], ),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('citizen_id', sa.UUID(), nullable=False),
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('mod_status', sa.Enum('visible', 'hidden', 'removed', name='comment_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.Enum('photo', 'video', 'document', name='evidence_type_enum'), nullable=False),
    sa.Column('storage_ref', sa.String(length=500), nullable=False),
    sa.Column('mod_status', sa.Enum('pending', 'approved', 'rejected', name='evidence_mod_status_enum'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['citizens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('citizen_id', sa.UUID(), nullable=False),
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('support', 'oppose', name='participation_type_enum'), nullable=False),
    sa.Column('oppose_explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('citizen_id', 'issue_id', name='uq_citizen_issue_participation')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participations')
    op.drop_table('evidence')
    op.drop_table('comments')
    op.drop_table('appeals')
    op.drop_table('verification_records')
    op.drop_table('notifications')
    op.drop_table('moderation_actions')
    op.drop_index('ix_issues_search_vector', table_name='issues', postgresql_using='gin')
    op.drop_index('ix_issues_district_status', table_name='issues')
    op.drop_index('ix_issues_created_at', table_name='issues')
    op.drop_index('ix_issues_category', table_name='issues')
    op.drop_table('issues')
    op.drop_table('citizens')
    op.drop_table('districts')
    # ### end Alembic commands ###
