"""add_email_auth

Revision ID: a3b28872aef3
Revises: 4f83b56ed279
Create Date: 2026-06-04 15:03:40.815207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3b28872aef3'
down_revision: Union[str, None] = '4f83b56ed279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citizens', sa.Column('email', sa.String(length=255), nullable=True))
    op.alter_column('citizens', 'phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.create_unique_constraint(None, 'citizens', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'citizens', type_='unique')
    op.alter_column('citizens', 'phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.drop_column('citizens', 'email')
    # ### end Alembic commands ###
